In [1]:
import numpy

In [2]:
numpy.__version__

'1.20.1'

In [3]:
import numpy as np

In [6]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [7]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
a[-1]

array([ 9, 10, 11, 12])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.empty(4)

array([1., 1., 1., 1.])

In [17]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

# Add, remove, and sort

In [18]:
arr = np.array([1,2,3,4,5,6,7,8])

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [25]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

# Shape and Size

In [30]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                         [[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                         [[0, 1, 2, 3],
                          [4, 5, 6, 7]]])


In [31]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [32]:
array_example.ndim

3

In [33]:
array_example.size

24

In [34]:
array_example.shape

(3, 2, 4)

In [35]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [36]:
arr_one.ndim

2

In [37]:
arr_one.size

5

In [38]:
arr_one.shape

(1, 5)

# Reshape

In [39]:
a = np.arange(6)

In [40]:
print(a)

[0 1 2 3 4 5]


In [45]:
b = a.reshape(2,3)

In [46]:
print(b)

[[0 1 2]
 [3 4 5]]


In [47]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Convert 1D to 2D 

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])

In [49]:
a.shape

(6,)

In [50]:
a2 = a[np.newaxis]

In [52]:
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [53]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [54]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [55]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [57]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [58]:
c = np.expand_dims(a, axis=0)
c

array([[1, 2, 3, 4, 5, 6]])

In [59]:
c.shape

(1, 6)

# Indexing and Slicing

In [60]:
data = np.array([1,2,3])

In [66]:
data[0:2]

array([1, 2])

In [67]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
five_up = (a >= 5)

print(a[five_up])
print(a[a >=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [72]:
10/4 == 2.5

True

In [74]:
a[a/2 == 0]

array([], dtype=int32)

In [75]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Creating Array from Existing Data

In [76]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [78]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [79]:
a_1 = np.array([[1,1],
               [2,2]])

a_2 = np.array([[3,3],
                [4,4]])

In [80]:
a_1

array([[1, 1],
       [2, 2]])

In [81]:
a_2

array([[3, 3],
       [4, 4]])

In [83]:
a_1 = np.array([[1,1],
               [2,2]])

In [84]:
a_2 = np.array([[3,3],
               [4,4]])

In [85]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [86]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [88]:
array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

NameError: name 'array' is not defined

# Basic Operation

In [90]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [91]:
a.sum()

10

In [95]:
b = np.array([[1,1],
    [2,2]])

b

array([[1, 1],
       [2, 2]])

In [96]:
b.sum(axis=0)

array([3, 3])

In [97]:
b.sum(axis = 1)

array([2, 4])

In [98]:
data = np.array([1,2])
data

array([1, 2])

In [99]:
ones = np.ones(2)
ones

array([1., 1.])

In [100]:
data + ones

array([2., 3.])

In [101]:
data * data

array([1, 4])

# Broadcasting

In [102]:
data

array([1, 2])

In [103]:
data / 2

array([0.5, 1. ])

#  More Array

In [107]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [108]:
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [109]:
A.sum()

4.8595784

In [111]:
A.min()

0.05093587

In [112]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [113]:
A.max()

0.82485143

In [114]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [115]:
A.std()

0.21392120766089617

# Matrices

In [117]:
np.array([[1,2],
         [3,4]])

array([[1, 2],
       [3, 4]])

In [118]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [119]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [122]:
np.random.random((3,2))

array([[0.41398685, 0.54505818],
       [0.9736343 , 0.29986809],
       [0.05486987, 0.40468312]])

# Matric Arithmetic

In [123]:
data = np.array([[1,2],
         [3,4]])

data

array([[1, 2],
       [3, 4]])

In [124]:
ones = np.ones([2,2])

In [125]:
ones

array([[1., 1.],
       [1., 1.]])

In [126]:
data + ones

array([[2., 3.],
       [4., 5.]])

In [130]:
ones_row = np.ones([1,2])

ones_row

array([[1., 1.]])

In [131]:
data + ones_row

array([[2., 3.],
       [4., 5.]])

# Dot Product

In [135]:
a_1 = np.array([[1,2,3], [4,5,6]])
               

a_2 = np.array([[7,8], [9,10], [11,12]])
                

print(a_1)
print(a_1.shape)
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [136]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [137]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


# Matrix Aggregation

In [138]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [139]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [140]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transposing and Reshaping

In [141]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [142]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [143]:
data_col = np.array([[1, 2, 3, 4, 5, 6,]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [144]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [151]:
arr = np.arange(6).reshape((2, 3)).T
print(arr)

[[0 3]
 [1 4]
 [2 5]]


# N-Dimensional Array

In [150]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5,6], [7,8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [152]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [153]:
print(np.random.random((4,3,2)))

[[[0.79996451 0.75241758]
  [0.31658853 0.16442389]
  [0.34824279 0.62153167]]

 [[0.63887691 0.84886179]
  [0.38373506 0.968259  ]
  [0.66003821 0.86352517]]

 [[0.09691186 0.51579104]
  [0.20429247 0.16465927]
  [0.79487479 0.33431916]]

 [[0.62697402 0.34560518]
  [0.26505035 0.88038045]
  [0.47437203 0.01114821]]]


# Flatten N-Dimensional Array

In [154]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [155]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [156]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined

# Working with math formulas

In [166]:
observed = np.random.random((3,2))
predictions = np.random.random((3,2))

In [167]:
observed

array([[0.24974284, 0.95684401],
       [0.41751127, 0.07978831],
       [0.4087568 , 0.29175118]])

In [168]:
predictions

array([[0.90358007, 0.7598085 ],
       [0.17506198, 0.99289062],
       [0.22285722, 0.3208332 ]])

In [169]:
observed.size

6

In [171]:
(1/observed.size) * np.sum(np.square(observed - predictions))

0.2323780013776211

In [173]:
n = observed.size

error = (1/n) * np.sum(np.square(observed - predictions))

In [174]:
error

0.2323780013776211